### ISSUE TITLE
Default app language should be Romanian

### ISSUE THREAD

**Issue by aniri** [code4romania/mon-vot-android-kotlin#17]
The strings files will contain an English and a Romanian version, but the default app version should be Romanian and not dependent on the users phone settings.

TBD: low priority: how to switch to English? All suggestions are welcome :smile:

**Comment by EuV** [comment]
Hello!

I see two possible solutions:
1. Move Romanian strings into `values/strings.xml` and English into `values-en/strings.xml`. Then English language will be selected only in case English is the system phone language, Romanian otherwise.
2. Add custom setting inside the application and patch `Configuration` (e.g.: https://stackoverflow.com/questions/2900023). The setting may be stored in db or prefs. This solution leads to UI change and therefore some update in Figma required.

Is the first solution enough?

And by the way, are there any test accounts or debug-mode available, so I can login and go through the app in case I'm not Romanian? :)

**Comment by aniri** [comment]
@EuV the users should initially see the Romanian version of the app even if they have the phone set to English. So I guess we need a config and the easiest possible way to implement switching between languages. You can use the following test account 0722222222 123456

**Comment by EuV** [comment]
Ok, I'll work on it.
Will there be guidance on the design?

**Comment by aniri** [comment]
@EuV we don't have anything prepared at the moment :( so we are open to suggestions :smile:
