### ISSUE TITLE
[Code quality] Add sonar github action for uploading analysis on sonarcloud on push to develop/master

### ISSUE THREAD

**Issue by aniri** [code4romania/mon-vot-android-kotlin#200]
See as an example:
https://github.com/code4romania/expert-consultation-api/blob/develop/.github/workflows/sonar.yml

**Comment by lukstbit** [comment]
Check my pull request. I don't have experience with sonarqube but  I  skimmed through their docs and implemented the integration. I can't test it with the live url but it works with a local instance of sonarqube. It even found a bug :) .

**Comment by aniri** [comment]
> Check my pull request. I don't have experience with sonarqube but I skimmed through their docs and implemented the integration. I can't test it with the live url but it works with a local instance of sonarqube. It even found a bug :) .

hmmm... the sonar build action fails with:
```
FAILURE: Build failed with an exception.
* What went wrong:
Project 'sonar' not found in root project 'Vote Monitor'.
```
But it seems to upload the analysis to sonarcloud...

I'll try and investigate why :thinking:

**Comment by lukstbit** [comment]
That happens because I used `./gradlew clean build sonar:sonar ...` from the repo you linked to(although locally I used the right task from the command line). It should be `./gradlew clean build sonar ...`(otherwise it will try to run the sonar task from a sonar project). Also, using the `build ` task seems to fail complaining about the `fastlane` keystore missing, but just building the debug app works
`./gradlew clean buildDebug sonar...`

**Comment by aniri** [comment]
@lukstbit looking good now :D this issue is closed now! thanks!
