### ISSUE TITLE
use appropriate lifecycle owner instead of "this" 

### ISSUE THREAD

**Issue by mrwhoknows55** [code4romania/mon-vot-android-kotlin#223]

**Comment by mrwhoknows55** [comment]
also lot of places `activity!!`, `parentFragment!!` is being used, which can be replaced by `requireActivity()` and `requireParentFragment()`

**Comment by lukstbit** [comment]
The changes you made are already present in #221

**Comment by mrwhoknows55** [comment]
@lukstbit Oh, I didn't knew about it. Should I close the PR?

**Comment by aniri** [comment]
@lukstbit @mrwhoknows55 thank you both for your help! yes, this issue was tackled in #221 , which is currently pending verification. I think we could keep it there and close the PR related to this one :/

Also, it would be awesome if you could offer some feedback on #221 as it brings a lot of changes :/
